### PR TITLE
#184797864 Admin should be able to CRUD users 

### PR DESCRIPTION
**Pull request by wilbrord2**
#### What does this PR do?

This PR is for enabling Admin to CRUD users 

#### Description of Task to be completed?
  
- [x] admin should be able to create user
- [x] admin should be able to read user
- [x] admin should be able to update user
- [x] admin should be able to delete a user
- [x]  test all these four end points
- [x] Document these four endpoints

#### How should this be manually tested?
- Clone this repo git clone https://github.com/atlp-rwanda/e-comm-team-amigos-bn
- Switch your working directory cd e-comm-team-amigos-bn
- Create an .env file and update it with .env-example
- Install all the dependencies by running npm install
- Then run the project by typing npm start
- You can use postman to test these API 
- you can use Swagger Documentation test these API

#### Endpoints to be tested:

1. `/users/create`
2. `/users/user/:id`
3. `/users/:id`
4. `/users/delete/:id`

#### Any background context you want to provide?
- Have Node Js installed in your local machine

#### What are the relevant pivotal tracker/Trello stories?

Story ID: [#184797864](https://www.pivotaltracker.com/story/show/184797864)

#### Screenshots (if appropriate)
Screenshot (156)
Screenshot (157)
Screenshot (158)
Screenshot (159)
Screenshot (160)
Screenshot (162)
Screenshot (161)

### CODE REVIEW

**Review by GasanaJr — APPROVED** [review]
LGTM

**Review by Mystica52 — COMMENTED** [review]
I can not update user on documentation

**Comment by wilbrord2** [comment]
> I can not update user on documentation

you can update now it is working

**Review by Rwibutso — APPROVED** [review]

**Review by AbdulKhaliq59 — APPROVED** [review]

**Review by Habinezajanvier — APPROVED** [review]
👍

**Pull request merged**
