### PR TITLE
#184581196 Search Product

### PR DESCRIPTION
**Pull request by AbdulKhaliq59**
#### What does this PR do?
This PR search product endpoint 

#### Description of Task to be completed?
- [x] Create search product endpoint
- [x] Swagger documentation for this this endpoint
- [x] test For this endpoint

#### How should this be manually tested?
- Clone this repo git clone [e-comm-team-amigos-bn](https://github.com/atlp-rwanda/e-comm-team-amigos-bn)
- Switch your working directory cd e-comm-team-amigos-bn
- Create an .env file and update it with `.env-example`
- Install all the dependencies by running `npm install`
- Then run the project by typing `npm start`

#### Endpoints to be tested:
-  `POST: product/create`
-  `GET: product/search`

#### Any background context you want to provide?
- Have Node Js installed in your local machine

#### What are the relevant pivotal tracker stories?

Story ID: [#184581196](https://www.pivotaltracker.com/story/show/184581196)

#### Screenshots (if appropriate)
screencapture-localhost-4000-docs-2023-03-22-09_45_03

Screenshot 2023-03-22 at 11 07 21

### CODE REVIEW

**Review by wilbrord2 — CHANGES_REQUESTED** [review]
After `user` (Buyer/Seller/Guest) search a product can you please remove `product Id ` and `user Id ` in `response` returned so that we can only see `product details`  you can also remove those  `created at` or `updated at` such things

**Review by GasanaJr — CHANGES_REQUESTED** [review]
Modify the response body to contain the info that interests the user. Otherwise this looks great.

**Review by nshutijonathan — APPROVED** [review]
LGTM

**Review by Emile-SHUMBUSHO — APPROVED** [review]

**Review by wilbrord2 — APPROVED** [review]
good work

**Review by GasanaJr — APPROVED** [review]

**Review by Habinezajanvier — CHANGES_REQUESTED** [review]
Where did you put our docker-related files

**Review by Habinezajanvier — APPROVED** [review]
👍

**Pull request merged**
