### PR TITLE
#184581199 Buyers should be able to checkout

### PR DESCRIPTION
**Pull request by GasanaJr**
#### What does this PR do?
This PR adds a checkout functionality to the e-commerce application
#### Description of Task to be completed?
- place an order
- checkout of the placed order
- update the `products` model accordingly
- save the relevant information to the `user` model
#### How should this be manually tested?
- clone this repo `git clone https://github.com/atlp-rwanda/e-comm-team-amigos-bn`
- switch your working directory `cd e-comm-team-amigos-bn`
- create an `.env` and update it with `.env-example`
- install all dependencies by running `npm install`
- in your terminal run `npm start`
#### Test the endpoints using Postman:
- post `/checkout` and provide the required information
#### Any background context you want to provide?
- PostgreSQL installed in your local machine
- Node JS installed in your local machine
#### Screenshots
- Screenshot 2023-04-03 at 10 04 21 AM
- Screenshot 2023-04-02 at 3 47 43 PM
- Screenshot 2023-04-01 at 2 50 40 AM
- Screenshot 2023-04-01 at 3 00 07 AM
- The first screenshot shows how to place an order and checkout
- The second screenshot confirms the order by updating the number of items from 2 to 0
- The third screenshot confirms the order through the `admin getAllOrders endpoint`. The last order is the one created in this process
#### What are the relevant pivotal tracker stories?
Story ID: [#184581199](https://www.pivotaltracker.com/story/show/184581199)

### CODE REVIEW

**Comment by Emile-SHUMBUSHO** [comment]
PaymentInfo is not handled on our server that's the job of Stripe API to ask card information.

**Review by ericndungutse — CHANGES_REQUESTED** [review]
Nice work, however, it's not required to create an order. Just submit an order id, get it and get it's associated products in `OrderProducts` table using `userId and orderId`. From there, you can structure checkout.

Moreover, `card info` is not required.

**Comment by GasanaJr** [comment]
> Nice work, however, it's not required to create an order. Just submit an order id, get it and get it's associated products in `OrderProducts` table using `userId and orderId`. From there, you can structure checkout.
> 
> Moreover, `card info` is not required.

So, meaning in checkout what I should is just ask for delivery info only???!!!!!!!

**Review by ericndungutse — APPROVED** [review]

**Review by nshutijonathan — APPROVED** [review]
LGTM

**Review by AbdulKhaliq59 — APPROVED** [review]

**Pull request merged**
