### PR TITLE
#184581178 Reset password via Email

### PR DESCRIPTION
**Pull request by Mystica52**
#### What does this PR do?
This PR reset a user password

#### Description of Task to be completed?
Have the following endpoint working
- /user/forgetPassword
user should enter the email and if it is database, it send the email for rest pasword with token link
- /user/resetPassword/{token}
user should enter the new password and update it

#### How should this be manually tested?
- Clone this repo git clone https://github.com/atlp-rwanda/e-comm-team-amigos-bn
- Switch your working directory cd e-comm-team-amigos-bn
- Create an .env file and update it with .env-example
- Install all the dependencies by running npm install
- Then run the project by typing npm start

#### Endpoints to be tested:
-Test endpoint using post man

#### Any background context you want to provide?
- Have Node Js installed in your local machine

#### What are the relevant pivotal tracker/Trello stories?

Story ID: [#184581178](https://www.pivotaltracker.com/story/show/184581178)

#### Screenshots (if appropriate)
Screenshot (16)
Screenshot (17)

### CODE REVIEW

**Review by AbdulKhaliq59 — CHANGES_REQUESTED** [review]
- resolve circleCi issue 
- add screenshot for swagger doc and test
- remove all `console.log()`

**Comment by 1MuhireDavid** [comment]
Hello @Mystica52 would you collect the PR description and remove the commit message inside there

**Review by wilbrord2 — CHANGES_REQUESTED** [review]
1. remove commit message in your PR description
2. Check your tests
3. remove all comments

**Review by khevin2 — APPROVED** [review]

**Review by AbdulKhaliq59 — APPROVED** [review]

**Review by ericndungutse — APPROVED** [review]
LGTM

**Review by wilbrord2 — APPROVED** [review]

**Review by wilbrord2 — CHANGES_REQUESTED** [review]
Please resolve Hound CI errors and we are good to go

**Review by wilbrord2 — APPROVED** [review]

**Review by nshutijonathan — CHANGES_REQUESTED** [review]
Please narrow down your commit messages to two or one  not four

**Review by Habinezajanvier — APPROVED** [review]
Smells good to me

**Pull request merged**
