### PR TITLE
#184581193 update cart in session

### PR DESCRIPTION
**Pull request by Mystica52**
**What does this PR do?**
This PR used for updating the cart
**Description of Task to be completed?**
Have the following endpoint working
• /cart/updatedCart 
   The updated cart should be stored in the buyer's session
The product details (name, price, image) should be retrieved from the database for each item in the updated cart
The new cart total should be calculated by summing the prices of the items in the updated cart
An updated cart confirmation message should be sent to the frontend to be displayed to the buyer 
**How should this be manually tested?**
• Clone this repo git clone https://github.com/atlp-rwanda/e-comm-team-amigos-bn
• Switch your working directory cd e-comm-team-amigos-bn
• Create an .env file and update it with .env-example
• Install all the dependencies by running npm install
• Then run the project by typing npm start
**Endpoints to be tested:**
-Test endpoint using post man
-Test endpoint in swagger documentation
**Any background context you want to provide?**
• Have Node Js installed in your local machine
**Screenshot**
Screenshot (34)

What are the relevant pivotal tracker/Trello stories?
Story ID: [#184581193](https://www.pivotaltracker.com/story/show/184581193)

### CODE REVIEW

**Review by AbdulKhaliq59 — APPROVED** [review]
Resolve conversation unless LGTM

**Review by AbdulKhaliq59 — APPROVED** [review]
Resolve conflict and conversation unless LGTM

**Review by ericndungutse — APPROVED** [review]
LGTM

**Review by wilbrord2 — COMMENTED** [review]
Please rebase and resolve those conflict with develop

**Comment by khevin2** [comment]
Resolve conflicts

**Review by GasanaJr — APPROVED** [review]
Good Job

**Review by Emile-SHUMBUSHO — APPROVED** [review]

**Review by khevin2 — APPROVED** [review]

**Review by Habinezajanvier — APPROVED** [review]
👍

**Pull request merged**
