### PR TITLE
#184797862 Admin should be able to do CRUD for product

### PR DESCRIPTION
**Pull request by Mystica52**
**What does this PR do?**
This PR used for admin should be able to do CRUD  for product
**Description of Task to be completed?**
Have the following endpoint working
`/admin/product`
   admin should get all product 
`/admin/product/:id`
   admin should get a product by id
` /admin/product/create/sellerId`
   admin should add product
`/admin/product/:id`
   admin should update product by id
 `/admin/product/:id`
   admin should delete product by id
**How should this be manually tested?**
• Clone this repo git clone https://github.com/atlp-rwanda/e-comm-team-amigos-bn
• Switch your working directory cd e-comm-team-amigos-bn
• Create an .env file and update it with .env-example
• Install all the dependencies by running npm install
• Then run the project by typing npm start
**Endpoints to be tested:**
-Test endpoint using post man
-admin can add when he has a seller id it mean that  admin should create the seller so that he can add product for him
**Any background context you want to provide?**	
• Have Node Js installed in your local machine
**What are the relevant pivotal tracker/Trello stories?**
Story ID: [#184797862](https://www.pivotaltracker.com/story/show/184797862)
**Screenshot**
image
image
image
image

### CODE REVIEW

**Review by AbdulKhaliq59 — APPROVED** [review]
Change label to ready for review unless It LGTM

**Review by AbdulKhaliq59 — APPROVED** [review]
- Change label
 - add screenshots
 Unless it LGTM

**Review by ericndungutse — APPROVED** [review]

**Comment by Emile-SHUMBUSHO** [comment]
In your PR description highlight  well those mentioned working endpoint otherwise LGTM

**Review by Emile-SHUMBUSHO — APPROVED** [review]

**Review by Habinezajanvier — APPROVED** [review]
👍

**Pull request merged**
