### PR TITLE
#184797860 Implement custom database seeder script

### PR DESCRIPTION
**Pull request by khevin2**
#### What does this PR do?
This PR add a functionality so that a user have basic testing data for the application

#### Description of Task to be completed?
- Add dummy users
- Add dummy orders
- Add dummy products
#### How should this be manually tested?
- Clone this repo git clone https://github.com/atlp-rwanda/e-comm-team-amigos-bn
- Switch your working directory cd e-comm-team-amigos-bn
- Create an .env file and update it with .env-example
- Install all the dependencies by running npm install
- Then run this functionality by typing `npm run seed`

#### Endpoints to be tested:
`$ npm run seed` to populate empty tables

#### Any background context you want to provide?
- Have Node Js installed in your local machine
- Have Postgres Server

#### What are the relevant pivotal tracker/Trello stories?

Story ID: [#184797860](https://www.pivotaltracker.com/story/show/184797860)

#### Screenshots (if appropriate)

Screenshot from 2023-03-28 18-38-36

### CODE REVIEW

**Review by Mystica52 — APPROVED** [review]

**Review by Mystica52 — APPROVED** [review]

**Review by wilbrord2 — APPROVED** [review]
good

**Review by wilbrord2 — APPROVED** [review]
resolve those conflicts and we are good to go

**Review by Rwibutso — APPROVED** [review]

**Comment by Rwibutso** [comment]
resolve those conflicts

**Review by AbdulKhaliq59 — APPROVED** [review]

**Review by AbdulKhaliq59 — APPROVED** [review]
resolve conflict unless It LGTM

**Review by Habinezajanvier — APPROVED** [review]
👍

**Pull request merged**
