### PR TITLE
#184797859: Implement pagination support for all get all endpoints

### PR DESCRIPTION
**Pull request by GasanaJr**
#### What does this PR do?
This PR reduces the number of items per page. A process called `pagination`
#### Description of Task to be completed?
- reduce the number of items per page to five to improve readability
#### How should this be manually tested?
- clone this repo `git clone https://github.com/atlp-rwanda/e-comm-team-amigos-bn`
- switch your working directory `cd e-comm-team-amigos-bn`
- create an `.env` and update it with `.env-example`
- install all dependencies by running `npm install`
- in your terminal run `npm run dev`
#### Test the endpoints using Postman:
- First populate the products relation through either seeders or the endpoint `/create`
- GET products: `/product/getAllItems` : This brings first five items
- GET products on the second page: `/product/getAllItems?page=2`
- Other get all endpoints can also be tested through the same approach mentioned above
#### Screenshots
- Screenshot 2023-03-28 at 6 14 50 AM
-  Screenshot 2023-03-28 at 6 15 53 AM
- Screenshot 2023-03-27 at 6 29 20 PM
- Screenshot 2023-03-27 at 6 32 52 PM
#### Any background context you want to provide?
- PostgreSQL installed in your local machine
- Node JS installed in your local machine
#### What are the relevant pivotal tracker stories?
Story ID: [#184797859](https://www.pivotaltracker.com/n/projects/2632829/stories/184797859)

### CODE REVIEW

**Comment by ericndungutse** [comment]
The implementation seems to be a client side technique, it does not optimize server. May be you should look into SKIP, and LIMIT from postgres.

**Comment by Emile-SHUMBUSHO** [comment]
Pagination works well as expected.

**Review by Emile-SHUMBUSHO — APPROVED** [review]

**Comment by GasanaJr** [comment]
> The implementation seems to be a client side technique, it does not optimize server. May be you should look into SKIP, and LIMIT from postgres.

I chose to go with this approach due to its flexibility and overall simplicity. It is a lot easier to customize the pagination behavior based on different requirements since the pagination logic is implemented in the application layer. However, I can look into this. Thanks for the feedback👊

**Comment by GasanaJr** [comment]
> The implementation seems to be a client side technique, it does not optimize server. May be you should look into SKIP, and LIMIT from postgres.

Now pagination uses LIMIT and OFFSET rather than being client side as you requested

**Review by wilbrord2 — APPROVED** [review]
Good job

**Review by Mystica52 — APPROVED** [review]

**Review by AbdulKhaliq59 — APPROVED** [review]
LGTM

**Review by Habinezajanvier — APPROVED** [review]
👍

**Pull request merged**
