### PR TITLE
#184581194 retrieve cart from buyer's session

### PR DESCRIPTION
**Pull request by Emile-SHUMBUSHO**
#### What does this PR do?
This PR creates an endpoint to allow users view their shopping cart

#### Description of Task to be completed?
- create endpoint for retrieving buyer's shopping cart
- document endpoint using swagger ui
- unit testing to test endpoint functionality

#### How should this be manually tested?
- Clone this repo git clone https://github.com/atlp-rwanda/e-comm-team-amigos-bn
- Switch your working directory cd e-comm-team-amigos-bn
- Create an .env file and update it with .env-example
- Install all the dependencies by running npm install
- Then run the project by typing npm start

#### Endpoints to be tested:
- view-cart
- clean-up-cart

#### Any background context you want to provide?
- Have Node Js installed in your local machine
- Have Postgres installed in your local machine or use elephanteSQL as online db

#### What are the relevant pivotal tracker/Trello stories?

Story ID: [#184581194](https://www.pivotaltracker.com/n/projects/2632829/stories/184581194)

#### Screenshots (if appropriate)
swagger ui endpoints
Screenshot 2023-03-23 at 23 36 54
Screenshot 2023-03-23 at 23 34 36

passed test
Screenshot 2023-03-23 at 23 44 48
#### Que

stions:

### CODE REVIEW

**Comment by khevin2** [comment]
There is a conflict with README file

**Comment by khevin2** [comment]
You may more screenshot to show your work

**Review by GasanaJr — CHANGES_REQUESTED** [review]
Add Screenshots of passing tests in the P.R. body. You may as well as rebase on develop to get the updated readme

**Review by ericndungutse — APPROVED** [review]
LGTM

**Comment by Emile-SHUMBUSHO** [comment]
> You may more screenshot to show your work

screenshot added

**Comment by Emile-SHUMBUSHO** [comment]
> There is a conflict with README file

conflict resolved

**Comment by Emile-SHUMBUSHO** [comment]
> Add Screenshots of passing tests in the P.R. body. You may as well as rebase on develop to get the updated readme

screenshot added

**Review by wilbrord2 — APPROVED** [review]

**Review by remy-mugisha — APPROVED** [review]

**Review by wilbrord2 — COMMENTED** [review]
Remove those conflicts

**Review by AbdulKhaliq59 — APPROVED** [review]
Resolve conflict unless LGTM

**Review by GasanaJr — APPROVED** [review]
LGTM

**Review by Habinezajanvier — APPROVED** [review]
👍

**Pull request merged**
